Blog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Blog.views.home', name='home'),
    url(r'^blog/', include('Jiga.urls', namespace='jiga')),

    url(r'^admin/', include(admin.site.urls)),
)

Jiga/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

from Jiga import views


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<post_id>\d+)$', views.post, name='post'),
    url(r'^post/(?P<post_id>\d+)/edit$', views.edit_post, name='edit_post'),
    url(r'^profile/(?P<user_id>\d+)$', views.profile, name='profile'),
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^new_post/', views.create_post, name='create_post'),
    url(r'^profile/edit', views.edit_profile, name='edit_profile'),
    url(r'^create_comment/(?P<post_id>\d+)$', views.create_comment, name='create_comment')
)

blog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'blog.views.home', name='home'),
    url(r'^blog/', include('jiga.urls', namespace='jiga')),

    url(r'^admin/', include(admin.site.urls)),
)

jiga/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

from jiga import views


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<post_id>\d+)$', views.post, name='post'),
    url(r'^post/(?P<post_id>\d+)/edit$', views.edit_post, name='edit_post'),
    url(r'^profile/(?P<user_id>\d+)$', views.profile, name='profile'),
    url(r'^profile/(?P<user_id>\d+)/follow$', views.follow, name='follow'),
    url(r'^profile/(?P<user_id>\d+)/unfollow$', views.unfollow, name='unfollow'),
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^new_post/', views.create_post, name='create_post'),
    url(r'^profile/edit', views.edit_profile, name='edit_profile'),
    url(r'^create_comment/(?P<post_id>\d+)$', views.create_comment, name='create_comment')

)

jiga/forms.py
from django import forms


class CommentForm(forms.Form):
    comment_title = forms.CharField()
    comment_text = forms.CharField(widget=forms.Textarea)


class EditProfileForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class PostForm(forms.Form):
    post_title = forms.CharField()
    post_text = forms.CharField(widget=forms.Textarea)
    pub_date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'id': 'datepicker'}))

    class Media(object):
        js = ('jiga/js/datepicker.js', )


class RegistrationForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField()
    first_name = forms.CharField()
    last_name = forms.CharField()

Jiga/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as _login
from django.contrib.auth import logout as _logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from Jiga.forms.comment import CommentForm
from Jiga.forms.edit_user_profile import EditProfileForm
from Jiga.forms.login import LoginForm
from Jiga.forms.post import PostForm
from Jiga.forms.registration import RegistrationForm
from Jiga.models import Post, Comment


def index(request):
    last_recently_posts = Post.objects.all().filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    return render(request, 'Jiga/index.html', {'last_recently_posts': last_recently_posts})


def post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    return render(request, 'Jiga/post.html', {'post': post, 'form': form})


@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.user != request.user:
        return HttpResponseRedirect(reverse('jiga:index'))
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post.post_title = form.cleaned_data['post_title']
            post.post_text = form.cleaned_data['post_text']
            post.pub_date = form.cleaned_data['pub_date']
            post.save()
            return HttpResponseRedirect(reverse('jiga:post', args=(post.id,)))

    else:
        form = PostForm(post.get_dict())
        form['pub_date'].css_classes('datepicker')
    return render(request, 'Jiga/post_form.html', {'form': form})


@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post_title = request.POST['post_title']
            post_text = request.POST['post_text']
            pub_date = request.POST['pub_date']
            user = request.user
            _post = Post(post_title=post_title, post_text=post_text, pub_date=pub_date, user=user)
            _post.save()
            return HttpResponseRedirect(reverse('jiga:post', args=(_post.id, )))
    else:
        form = PostForm()
    return render(request, 'Jiga/post_form.html', {'form': form})


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None and user.is_active:
                _login(request, user)
                return HttpResponseRedirect(reverse('jiga:profile', args=(user.id,)))
            else:
                    return render(request, 'Jiga/login.html', {'form': form})
    else:
        form = LoginForm()
    return render(request, 'Jiga/login.html', {'form': form})


def logout(request):
    _logout(request)
    return HttpResponseRedirect(reverse('jiga:index'))


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            user = User(username=username, email=email,
                        first_name=first_name, last_name=last_name)
            user.set_password(password)
            try:
                user.save()   # TODO: validate for multiply user
            except IntegrityError:
                return render(request, 'Jiga/registration.html',
                              {'form': form, 'error_message': 'A user with this name already exists'})
            return HttpResponseRedirect(reverse('jiga:profile', args=(user.id,)))
    else:
        form = RegistrationForm()
    return render(request, 'Jiga/registration.html', {'form': form})


def profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if user == request.user:
        posts = user.post_set.all().order_by('-pub_date')
    else:
        posts = user.post_set.all().filter(pub_date__lte=timezone.now()).order_by('-pub_date')
    return render(request, 'Jiga/profile.html', {'user_for_viewing': user, 'posts': posts})

@login_required
def edit_profile(request):
    user = request.user
    if request.method == 'POST':
        form = EditProfileForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            user.first_name = first_name
            user.last_name = last_name
            user.save()
            return HttpResponseRedirect(reverse('jiga:profile', args=(user.id, )))
    else:
        form = EditProfileForm({'first_name': user.first_name, 'last_name': user.last_name})
    return render(request, 'Jiga/edit_user_profile.html', {'form': form})



@login_required
def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    user = request.user
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_title = form.cleaned_data['comment_title']
            comment_text = form.cleaned_data['comment_text']
            comment = Comment(comment_title=comment_title, comment_text=comment_text,
                              user=user, post=post,pub_date=timezone.now())
            comment.save()
    return HttpResponseRedirect(reverse('jiga:post', args=(post.id, ) ))

jiga/views.py
from datetime import datetime
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_auth
from django.contrib.auth import logout as logout_auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils import timezone

from .forms import CommentForm, EditProfileForm, LoginForm, PostForm, RegistrationForm
from .models import Post, Comment, Relationship


def index(request):
    last_recently_posts = Post.objects.all().filter(pub_date__lte=timezone.now()).order_by('-pub_date')
    error_message = None
    get_query = request.GET
    if get_query:
        try:
            since = datetime.strptime(get_query['since'],'%Y-%m-%d %H:%M')
            to = datetime.strptime(get_query['to'],'%Y-%m-%d %H:%M')
            last_recently_posts = Post.objects.all().filter(pub_date__gte=since, pub_date__lte=to)
        except ValueError:
            error_message = 'Bad time format'
    return render(request, 'jiga/index.html', {'last_recently_posts': last_recently_posts, 'error_message': error_message})


def post(request, post_id):
    post_obj = get_object_or_404(Post, pk=post_id)

    if post_obj.pub_date > timezone.now() and request.user != post_obj.user:
        return HttpResponseRedirect(reverse('jiga:index'))
    title = post_obj.post_title
    post_comments = post_obj.comment_set.all().order_by('pub_date')
    form = CommentForm()
    return render(request, 'jiga/post.html', {'post': post_obj, 'form': form,
                                              'title': title, 'post_comments':post_comments})


@login_required
def edit_post(request, post_id):
    post_obj = get_object_or_404(Post, pk=post_id)
    if post_obj.user != request.user:
        return HttpResponseRedirect(reverse('jiga:index'))
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post_obj.post_title = form.cleaned_data['post_title']
            post_obj.post_text = form.cleaned_data['post_text']
            post_obj.pub_date = form.cleaned_data['pub_date']
            post_obj.save()
            return HttpResponseRedirect(reverse('jiga:post', args=(post_obj.id,)))
    else:
        form = PostForm(post_obj.get_dict())
        form['pub_date'].css_classes('datepicker')
    return render(request, 'jiga/forms.html', {'form': form})


@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post_title = request.POST['post_title']
            post_text = request.POST['post_text']
            pub_date = request.POST['pub_date']
            user = request.user
            _post = Post(post_title=post_title, post_text=post_text, pub_date=pub_date, user=user)
            _post.save()
            return HttpResponseRedirect(reverse('jiga:post', args=(_post.id, )))
    else:
        form = PostForm()
    return render(request, 'jiga/forms.html', {'form': form})


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None and user.is_active:
                login_auth(request, user)
                return HttpResponseRedirect(reverse('jiga:profile', args=(user.id,)))
            else:
                return render(request, 'jiga/forms.html', {'form': form})
    else:
        form = LoginForm()
    return render(request, 'jiga/forms.html', {'form': form})


def logout(request):
    logout_auth(request)
    return HttpResponseRedirect(reverse('jiga:index'))


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            user = User(username=username, email=email,
                        first_name=first_name, last_name=last_name)
            user.set_password(password)
            try:
                user.save()   # TODO: validate for multiply email
            except IntegrityError:
                return render(request, 'jiga/forms.html',
                              {'form': form, 'error_message': 'A user with this name already exists'})
            return HttpResponseRedirect(reverse('jiga:profile', args=(user.id,)))
    else:
        form = RegistrationForm()
    return render(request, 'jiga/forms.html', {'form': form})


def profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    followed = None
    if user == request.user:
        posts = user.post_set.all().order_by('-pub_date')
    else:
        followed = following(request.user, user)
        posts = user.post_set.all().filter(pub_date__lte=timezone.now()).order_by('-pub_date')
    list_recently_comments = user.comment_set.all().order_by('-pub_date')[:5]
    list_followed_user = user.from_user.all()
    list_follower_user = user.to_user.all()
    return render(request, 'jiga/profile.html', {'user_for_viewing': user, 'posts': posts,
                                                 'list_recently_comments': list_recently_comments,
                                                 'list_followed_user': list_followed_user,
                                                 'list_follower_user': list_follower_user,
                                                 'followed': followed })


@login_required
def edit_profile(request):
    user = request.user
    if request.method == 'POST':
        form = EditProfileForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            user.first_name = first_name
            user.last_name = last_name
            user.save()
            return HttpResponseRedirect(reverse('jiga:profile', args=(user.id, )))
    else:
        form = EditProfileForm({'first_name': user.first_name, 'last_name': user.last_name})
    return render(request, 'jiga/forms.html', {'form': form})


@login_required
def create_comment(request, post_id):
    post_obj = get_object_or_404(Post, pk=post_id)
    user = request.user
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_title = form.cleaned_data['comment_title']
            comment_text = form.cleaned_data['comment_text']
            comment = Comment(comment_title=comment_title, comment_text=comment_text,
                              user=user, post=post_obj, pub_date=timezone.now())
            comment.save()
    return HttpResponseRedirect(reverse('jiga:post', args=(post_obj.id, )))


@login_required
def follow(request, user_id):
    from_user = request.user
    to_user = get_object_or_404(User, pk=user_id)
    if to_user != from_user:
        new_relationship = Relationship(from_user=from_user, to_user=to_user)
        new_relationship.save()
        return HttpResponseRedirect(reverse('jiga:profile', args=(user_id, )))
    return HttpResponseRedirect(reverse('jiga:profile', args=(user_id, )))


def unfollow(request, user_id):
    from_user = request.user
    res = Relationship.objects.filter(from_user__id=from_user.id,
                                      to_user__id=user_id)
    if res is not None:
        res.delete()
    return HttpResponseRedirect(reverse('jiga:profile', args=(user_id, )))


def following(from_user, to_user):
    if Relationship.objects.filter(from_user__id=from_user.id,
                                   to_user__id=to_user.id):
        return True
    return False

jiga/templates/jiga/application_layout.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>

    <title>{{ title }}</title>
    {% load staticfiles %}
    <link type="text/css" rel="stylesheet" href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
    <link type="text/css" rel="stylesheet" href="{% static 'jiga/css/bootstrap.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'jiga/css/timepicker.css' %}">
    <style>
        body {
            padding-top: 50px;
        }
    </style>
    {% block head %} {% endblock %}
</head>
<body>
    {% include 'jiga/header.html' %}

    <div class="container">
        {% block content %}


        {% endblock %}
    </div>
    <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

    <script src="{% static 'jiga/js/bootstrap.js' %}"></script>
    <script src="{% static 'jiga/js/timepicker.js' %}"></script>
    {% block scripts %} {% endblock %}

</body>

</html>

jiga/templates/jiga/forms.html
{% extends 'jiga/application_layout.html' %}

{% block content %}

    <form method="post">
        {% csrf_token  %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>

{% endblock %}


{% block scripts %}
    {{ form.media }}
{% endblock %}

jiga/templates/jiga/header.html
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'jiga:index' %}">Home</a></li>


                {% if user.is_authenticated %}
                    <li><a href="{% url 'jiga:create_post' %}">New post</a></li>
                    <li><a href="{% url 'jiga:profile' user.id %}">My profile</a></li>
                    <li><a href="{% url 'jiga:logout' %}">Log out</a></li>
                {% else %}
                    <li><a href="{% url 'jiga:login' %}">Log in</a></li>
                    <li><a href="{% url 'jiga:register' %}">Sign in</a></li>
                {% endif %}


          </ul>
        </div><!--/.nav-collapse -->
      </div>
</div>

jiga/templates/jiga/index.html
{% extends 'jiga/application_layout.html' %}


{% block scripts %}
    <script>
        $(".datepicker").datetimepicker({
            dateFormat: 'yy-mm-dd'
        });
    </script>
{% endblock %}


{% block content %}
    <h2> content </h2>
    {% if last_recently_posts %}
        <table class="table">
            <thead>
                <td>#</td>
                <td>Title</td>
                <td>
                    <form action="{% url 'jiga:index' %}" method="get">
                        Pub date:
                        since:<input type="date" name="since" class="datepicker" />
                        to:<input type="date" name="to" class="datepicker" />
                        <input type="submit" value="Filtre">
                    </form>
                </td>
                <td>Link to</td>
            </thead>
            {% for post in last_recently_posts %}
                <tr>
                    <td> {{ forloop.counter }}</td>
                    <td> {{ post.post_title }}</td>
                    <td> {{  post.pub_date  }}</td>
                    <td> <a href="{% url 'jiga:post' post.id %}">Go to</a> </td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
    {% if error_message %}
        <script>
            alert('{{ error_message }}');
        </script>
    {% endif %}
{% endblock %}

jiga/templates/jiga/post.html
{% extends 'jiga/application_layout.html' %}

    {% block head %}
    <style>
        .comment {
            border: dashed #080808;
            margin: 10px 10px 10px 10px;
        }
        #comment_set {
            border:  solid #269abc;

        }
    </style>
   {% endblock %}


{% block content %}
    <div class="row row-offcanvas row-offcanvas-right">
        <p>
            <div class="jumbotron">
                <h1>{{ post.post_title }} -- {{ post.user.first_name }} {{ post.user.last_name }}</h1>
                <p>{{ post.post_text }}</p>
                {% if user == post.user %}
                    <a href="{% url 'jiga:edit_post' post.id %}">Edit post</a>
                {% endif %}
            </div>
        </p>
        <div class="col-xs-12 col-sm-9">
            <div id="comment_set">
                {% for comment in post_comments %}
                <div class="comment">
                    <p>{{ comment.comment_title }} -- {{ comment.user.first_name }}
                        {{ comment.user.last_name }} | {{ comment.pub_date }}
                    </p>
                    {{ comment.comment_text }}
                </div>
                {% endfor %}
            </div>
            <br /> <br/>
            {% if user.is_authenticated  %}
                <div id="add_comment">
                    <form method="post" action="{% url 'jiga:create_comment' post.id %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Add comment" />
                    </form>
                </div>
            {% endif %}
        </div>

        <div id="sidebar" class="col-xs-6 col-sm-3 sidebar-offcanvas" rove="navigation">
            <p>Author:</p>
            <div class="list-group">
                <p class="list-group-item"> {{ post.user.first_name }} {{ post.user.last_name }}
                {{ post.pub_date }}</p>
            </div>
        </div>
    </div>

{% endblock %}

jiga/templates/jiga/profile.html
{% extends 'jiga/application_layout.html' %}

{% block content %}
    <div class="row row-offcanvas row-offcanvas-right">
        <p>
        <div class="jumbotron">
            <h1>{{ user_for_viewing.first_name }} {{ user_for_viewing.last_name }}</h1>
            <p>This is an example to show the potential of an offcanvas layout pattern in Bootstrap.
                Try some responsive-range viewport sizes to see it in action.</p>
            {% if user == user_for_viewing %}
                <a href="{% url 'jiga:edit_profile' %}"> Edit profile </a>
            {% elif not followed %}
                <a href="{% url 'jiga:follow' user_for_viewing.id %}"> Follow </a>
            {% else %}
                <a href="{% url 'jiga:unfollow' user_for_viewing.id %}"> Unfollow </a>
            {% endif %}
          </div>
        </p>

        <div class="col-xs-12 col-sm-9">
            <h2>Post's:</h2>
            <table class="table">
                <thead>
                    <td>#</td>
                    <td>Title</td>
                    <td>Date of pub</td>
                    <td>Link to</td>
                </thead>
                {% for post in posts %}
                    <tr>
                        <td> {{ forloop.counter }}</td>
                        <td> {{ post.post_title }}</td>
                        <td> {{  post.pub_date  }}</td>
                        <td> <a href='{% url 'jiga:post' post.id %}'> Go to </a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>

        <div id="sidebar" class="col-xs-6 col-sm-3 sidebar-offcanvas" rove="navigation">
            <p>Last comments:</p>
            <div class="list-group">
                {% for comment in list_recently_comments %}
                    <a class="list-group-item" href="{% url 'jiga:post' comment.post.id %}">Post:
                        {{ comment.post }}</a>
                {% endfor %}
            </div>
            <p> Followed: </p>
            <div class="list-group">
                {% for relation in list_followed_user %}
                    <a class="list-group-item" href="{% url 'jiga:profile' relation.to_user.id %}">
                        {{ relation.to_user.first_name}} {{ relation.to_user.last_name  }} </a>
                {% endfor %}

            </div>
            <p> Followers:</p>
            <div class="list-group">
                {% for relation in list_follower_user %}
                    <a class="list-group-item" href="{% url 'jiga:profile' relation.from_user.id %}">
                        {{ relation.from_user.first_name}} {{ relation.from_user.last_name  }} </a>
                {% endfor %}
            </div>

        </div>

    </div>

    <hr>


    <footer>
            <p>&copy; Company 2014</p>
    </footer>

{% endblock %}